name: 'Simple Github Action'

on:
  push:

permissions:
  contents: read

concurrency: testing

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Greeting
        run: echo $GREETING, $USER.
        shell: bash
        env:
          GREETING: OK
      - name: List files
        run: "pwd && ls"
        shell: bash
