name: 'Simple Github Action'

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

concurrency: testing

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Greeting
        run: echo $GREETING, $USER.
        shell: bash
        env:
          GREETING: OK
      - name: List files
        run: "pwd && ls"
        shell: bash

  stage2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        # https://github.com/gradle/gradle-build-action
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: sh ./gradlew build

      - name: Execute Sonar
        run: sh ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
